### PR TITLE
Removed an outdated reference to a guide that no longer exists.

### PR DESCRIPTION
**Pull request by mig281**
The _Amazon SQS Getting Started Guide_ has been retired. The most current information is in the _Amazon SQS Developer Guide_: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-tutorials.html

### CODE REVIEW

**Comment by JensRantil** [comment]
> The most current information is in the Amazon SQS Developer Guide

Why not change the link to that instead?

**Comment by mig281** [comment]
@JensRantil Sounds good! I've added the link. Could you please pull in the change?

**Comment by JensRantil** [comment]
@mig281 I'm not a maintainer, so unfortunately I can't do that.

**Comment by mig281** [comment]
@lukaszx0 Could _you_ please merge in this change? :smile:
Thanks!

**Comment by mig281** [comment]
@lukaszx0 @flaper87 @mariano @ilndinesh Hi, guys. Could one of you please merge in this change? You're currently linking to a non-existing guide... Thanks! :smiley:

**Comment by lukaszx0** [comment]
Thanks everybody!

**Comment by mig281** [comment]
Thank you! :+1:

**Pull request merged**
