### PR TITLE
Add details about Azure Service Bus

### PR DESCRIPTION
**Pull request by axisc**
Azure Service Bus is a fully managed Enterprise Messaging PaaS offering that provides familiar Point-to-point and Pub-sub semantics.

### CODE REVIEW

**Comment by axisc** [comment]
Hi @lukaszx0 , I'm from the Azure Service Bus team @ Microsoft - Could I request your review for the same?

**Comment by axisc** [comment]
@lukaszx0 - any update on this PR?

**Comment by axisc** [comment]
@lukaszx0 following up on this PR

**Comment by lukaszx0** [comment]
The site has been effectively abondened for a long time now and I've always been a very bad steward of it. Also, I don't think it serves the purpose it used to serve so I'm archiving this repo and taking the site down. Sorry and thanks for your contributions!

**Pull request closed without merging**
